### PR TITLE
Both ip versions

### PR DESCRIPTION
**Pull request by IvBaranov**
Current version of RxBonjour returns one random host IP of _BonjourService_ if there were actually both IPv4 and IPv6 versions.
I need specific host IP.

### CODE REVIEW

**Comment by mannodermaus** [comment]
Thank you for your contribution! I will look through your PR shortly.

**Comment by mannodermaus** [comment]
I have read through and commented on your proposed changes. Thanks again for taking your time to contribute to RxBonjour!

**Comment by IvBaranov** [comment]
Thanks for detailed notes. Sorry for that mess. Here is commit according to your comments.

**Comment by mannodermaus** [comment]
Looks good! Please rename the InetAddress accessor methods according to my comments and we're good to go!

edit: Actually, since this is such a minor change, I'll do it myself. The syntax will be `getV4Host()` and `getV6Host()` respectively. Thanks for your addition!

**Comment by mannodermaus** [comment]
Released in 0.3.0

**Pull request merged**
