### PR TITLE
Added service registration

### PR DESCRIPTION
**Pull request by i906**
Hi, I have added service registration for RxBonjour. Please take a look.

Sample usage:

``` java
RxBonjour.newBroadcast("_awesome-chat._tcp")
    .name(Build.MODEL)
    .addTxtRecord("version", BuildConfig.VERSION_NAME)
    .port(4906)
    .build()
    .start(this)
    .subscribeOn(Schedulers.io())
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe(new Action1<BonjourEvent>() {
        @Override
        public void call(BonjourEvent broadcastState) {
            /* ... */
        }
    });
```

### CODE REVIEW

**Comment by mannodermaus** [comment]
Awesome! I will dive into this later this week, but thanks so much for your contribution!

**Comment by pepijntb** [comment]
Hi, how can I unregister the service?

**Comment by i906** [comment]
@pepijntb Unsubscribing the observable will unregister the service.

**Comment by pepijntb** [comment]
@i906 thx. It's working!

**Comment by mannodermaus** [comment]
I have reviewed the PR and it looks great, however I will change some implementation details regarding the Broadcast class (I'd rather not keep a reference to the Builder instance after creation). Thank you for the contribution!

**Pull request merged**
