### PR TITLE
Update jmDNS library

### PR DESCRIPTION
**Pull request by i906**
There were some issues compiling my app with Proguard. Updating the jmDNS library to a newer one solved the issues.

### CODE REVIEW

**Comment by mannodermaus** [comment]
Thanks! I'll review this shortly. What kind of issue did you face with the old version of JmDNS?

**Comment by i906** [comment]
When enabled Proguard I'll get an error message during compilation:

```
Warning:javax.jmdns.impl.DNSCache: can't find referenced method 'java.util.concurrent.ConcurrentHashMap$KeySetView keySet()' in program class javax.jmdns.impl.DNSCache
Warning:there were 1 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
```

After upgrading the library and adding `-dontwarn org.slf4j.**` to my Proguard rules, it compiled fine.

**Comment by mannodermaus** [comment]
The issue here is that `ConcurrentHashMap.KeySetView` has only been added in Java 8. Proguard trips up because it doesn't know how to deal with this class when processing within a pre-Java-8 Android environment, where `ConcurrentHashMap#keySet()` would simply return a `Set` of keys instead of this new `KeySetView`. I assume you are building with JDK 8?

I suppose you would have been fine with just `-dontwarn javax.jmdns.**` before, but it's great to know that the latest version of JmDNS seems to work without that. I plan to release the next version, which will include this change, on the weekend, preferably alongside some proper `consumerProguardFiles`! Thanks again for your contribution.

**Comment by i906** [comment]
Yes, you are correct that I am building with JDK 8 (using Retrolambda). I did want to add those `consumerProguardFiles` but I may have missed that.

Thanks for the explanation.

**Pull request merged**
